site_name: Working Memory Architecture and Demand (WoMAD) Model
site_url: https://saamehsanaaee.github.io/WoMAD/

nav:
  - Home: 'index.md'
  - The Code: 'the_code.md'
  - The Science: 'the_science.md'

theme:
  name: simple-blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
