site_name: Working Memory Architecture and Demand (WoMAD) Model
site_url: https://saamehsanaaee.github.io/WoMAD/

nav:
  - WoMAD Home: 'index.md'
  - The Code: 'the-code.md'
  - The Science: 'the-science.md'
  - Logs: 'logs/index.md'

theme:
  name: simple-blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
